<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Bebekon.Core/Bebekon.Core.csproj" />
    <Content Include="../../core/xray.exe" Link="core/xray.exe" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="../../core/sing-box.exe" Link="core/sing-box.exe" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
