namespace Bebekon.App;
public static class I18n
{
    public static bool English { get; private set; }
    public static string T(string ru, string en) => English ? en : ru;
    private static readonly (string Key, string Ru, string En)[] Labels = [
        ("ApplicationShortcutDetail","Выбор программ","Choose applications"),("AdminShortcutDetail","Админ и сервисы","Admin and services"),
        ("AccentTitle","Акцентный цвет","Accent color"),("AccentDetail","Единая палитра кнопок, подсветки и переключателей.","A consistent palette for buttons, highlights and switches."),
        ("SubscriptionLink","Вставьте ссылку на подписку","Paste a subscription link"),("ImportLink","Добавить и применить","Add and apply"),("ImportingLink","Загружаем серверы…","Loading servers…"),
        ("Cyan","Бирюзовый","Turquoise"),("Blue","Голубой","Blue"),("Emerald","Изумрудный","Emerald"),("Violet","Лавандовый","Lavender"),
        ("AnimationTitle","Плавные анимации","Smooth animations"),("AnimationDetail","Переходы страниц и отклик элементов. Учитывает настройки Windows.","Page transitions and interaction feedback. Respects Windows settings."),
        ("GlowTitle","Мягкое свечение","Soft glow"),("GlowDetail","Ореол логотипа и кнопки подключения. Пульсирует при активном VPN.","Logo and connection button halos. Pulses while VPN is connected."),
        ("PureBlackTitle","Чистый чёрный","Pure black"),("PureBlackDetail","Чёрный фон для OLED-экранов.","Black background for OLED displays."),
        ("LatencyHelp","VPN: время HTTPS-запроса через выбранный сервер. TCP: открытие порта; другой VPN может перехватить соединение и занизить результат.","VPN: HTTPS request time through the selected server. TCP: port connection; another VPN may intercept it and understate latency."),
        ("MinimizeWindow","Свернуть","Minimize"),("MaximizeWindow","Развернуть","Maximize"),("RestoreWindow","Восстановить","Restore"),("CloseWindow","Закрыть","Close"),
        ("Home","Главная","Home"),("Servers","Серверы","Servers"),("Rules","Правила","Rules"),("Subscriptions","Подписки","Subscriptions"),("Settings","Настройки","Settings"),
        ("ServerTitle","Выбор сервера","Choose a server"),("ServerSubtitle","Узлы из вашей подписки","Nodes from your subscription"),("SearchServers","Поиск сервера","Search servers"),("ByLatency","По пингу","By latency"),("ByName","По названию","By name"),("Fast","TCP (порт)","TCP (port)"),("Exact","VPN (точный)","VPN (exact)"),
        ("RoutingTitle","Маршрутизация","Routing"),("RoutingSubtitle","Куда направлять трафик","Where your traffic goes"),("EntirePc","Весь ПК","Entire PC"),("EntireDetail","Весь трафик через VPN","All traffic through VPN"),("ByRules","По правилам","By rules"),("RulesDetail","Остальное — напрямую","Everything else goes direct"),
        ("Applications","Приложения","Applications"),("ApplicationsDetail","Выберите программы, которые будут идти через VPN","Choose programs that use VPN"),("Open","Открыть","Open"),("Presets","Готовые правила","Service presets"),("PresetsDetail","Telegram, YouTube, Discord, ChatGPT, Claude…","Telegram, YouTube, Discord, ChatGPT, Claude…"),("AddPreset","Добавить набор","Add a preset"),("MyRules","Мои правила","My rules"),("Add","Добавить","Add"),("CreateProfile","Создать профиль","Create profile"),("SearchRules","Поиск по правилам","Search rules"),("RuleTip","Правила сверху имеют приоритет. Перетащите строку, чтобы изменить порядок.","Higher rules take priority. Drag a row to reorder."),
        ("AddSubscription","Добавить подписку","Add subscription"),("SubscriptionDetail","Вставьте ссылку провайдера — серверы появятся автоматически","Paste your provider link to load servers"),("Update","Обновить","Update"),("Edit","Изменить","Edit"),("Delete","Удалить","Delete"),("NoSubscriptions","Здесь появится ваша подписка","Your subscription will appear here"),("NoServers","Добавьте первую подписку","Add your first subscription"),("NoServersDetail","Ссылка Ultima или любого VLESS-провайдера","Ultima or any VLESS provider link"),("NoRules","Добавьте сайты или приложения","Add websites or applications"),("NoRulesDetail","Без правил весь трафик идёт напрямую","Without rules all traffic goes direct"),
        ("Server","СЕРВЕР","SERVER"),("Mode","РЕЖИМ","MODE"),("Session","сессия","session"),("VpnIp","VPN IP-АДРЕС","VPN IP ADDRESS"),("VpnIpDetail","Внешний адрес выбранного VPN-сервера","Public address of the selected VPN server"),("Mbps","Мбит/с","Mbps"),("Proxy","Прокси","Proxy"),
        ("SettingsDetail","Оформление · сеть · поведение","Appearance · network · behavior"),("Language","Язык","Language"),("Startup","Запускать вместе с Windows","Start with Windows"),("Tray","Сворачивать в трей","Minimize to tray"),("AutoConnect","Подключаться автоматически","Connect automatically"),("RestoreServer","Восстанавливать последний сервер","Restore last server"),("Notifications","Показывать уведомления","Show notifications"),("DnsProtection","Защита DNS","DNS protection"),("DnsDetail","Прямой DNS для обычных сайтов, VPN DNS для выбранных","Direct DNS for normal sites, VPN DNS for selected sites"),("Advanced","Дополнительно","Advanced"),("Compatibility","Совместимость с Docker / VM","Docker / VM compatibility"),("ConfigFolder","Папка настроек","Settings folder"),("LogsFolder","Открыть логи","Open logs"),("RestartService","Перезапустить службу","Restart service"),("SaveSettings","Сохранить настройки","Save settings"),("ProxyNote","Прокси использует 127.0.0.1:17890. Правила приложений требуют TUN.","Proxy uses 127.0.0.1:17890. Application rules require TUN."),
        ("Import","Импорт профиля","Import profile"),("Export","Экспорт профиля","Export profile"),("DeleteProfile","Удалить профиль","Delete profile"),
        ("SearchSettings","Поиск по настройкам","Search settings"),("Appearance","Оформление","Appearance"),("Network","Сеть","Network"),("Behavior","Поведение","Behavior"),("AllSettings","Все настройки","All settings"),
        ("TunMode","TUN-режим","TUN mode"),("TunDetail","Системный туннель для сайтов и приложений. Выбирается при запуске.","System tunnel for websites and applications. Selected on startup."),
        ("SystemProxy","Системный прокси","System proxy"),("SystemProxyDetail","Для приложений с поддержкой прокси. Переключает режим TUN.","For proxy-aware applications. Switches off TUN mode."),
        ("DnsProtectionDetail","Помогает предотвратить обход системного DNS в режиме TUN.","Helps prevent bypassing system DNS in TUN mode."),
        ("DnsResolver","DNS-резолвер","DNS resolver"),("HelperTitle","Служба подключения","Connection helper"),("HelperDetail","Поднимает TUN с нужными правами. Установка требует UAC один раз.","Creates TUN with the required rights. Installation needs UAC once."),("RestartShort","Перезапустить","Restart"),
        ("CompatibilityDetail","Смягчает сетевые ограничения для виртуальных машин и контейнеров.","Relaxes network restrictions for virtual machines and containers."),
        ("LanguageDetail","Язык навигации и элементов интерфейса.","Language of navigation and interface controls."),("ThemeTitle","Цветовая тема","Color theme"),("ThemeDetail","Спокойный тёмный фон и контрастные элементы.","A calm dark background and clear contrast."),("DarkTheme","Тёмная","Dark"),
        ("StartupDetail","Открывать приложение в трее при входе в Windows.","Open the application in the tray on Windows sign-in."),("TrayDetail","Закрытие окна оставляет приложение в области уведомлений.","Closing the window keeps the app in the notification area."),
        ("AutoConnectDetail","Подключаться к выбранному серверу при запуске.","Connect to the selected server on startup."),("RestoreServerDetail","Запоминать выбранный сервер между запусками.","Remember the selected server between launches."),("NotificationsDetail","Сообщать о подключении и ошибках, когда окно скрыто.","Show connection and error notifications when the window is hidden."),
        ("MtuDetail","Размер сетевого пакета. По умолчанию 1500; допустимо 1280–9000.","Network packet size. Default 1500; range 1280–9000."),
        ("ConfigDetail","Подписки, профили и настройки хранятся с шифрованием Windows.","Subscriptions, profiles and settings use Windows encryption."),
        ("LogsTitle","Журнал событий","Event log"),("LogsDetail","События подключения для диагностики неполадок.","Connection events for troubleshooting."),("CoreTitle","Версия ядра","Core version"),("CoreDetail","Официальная стабильная версия sing-box для Windows x64.","Official stable sing-box version for Windows x64."),
        ("NothingFound","Ничего не найдено","No results"),("TrySearch","Попробуйте другой поисковый запрос","Try a different search"),
        ("SaveDetail","Параметры сети применятся при сохранении.","Network settings apply when saved."),
        ("PingAll","Проверить задержку серверов","Check server latency"),("ViewMode","Переключить вид списка","Switch list layout"),("Unsupported","Не поддерживается этой версией","Not supported by this version"),
        ("DownloadSpeed","Загрузка","Download"),("UploadSpeed","Отправка","Upload"),("Cancel","Отмена","Cancel"),("ProtectedLink","Защищённая ссылка","Protected link"),("SubscriptionCount","Серверы из подписки","Subscription servers")
    ];
    public static void Set(string language) { English = language == "English"; foreach (var (key, ru, en) in Labels) Application.Current.Resources[key] = English ? en : ru; }
}
