namespace Bebekon.App;
public static class I18n
{
    public static bool English { get; private set; }
    public static string T(string ru, string en) => English ? en : ru;
    private static readonly (string Key, string Ru, string En)[] Labels = [
        ("Home","Главная","Home"),("Servers","Серверы","Servers"),("Rules","Правила","Rules"),("Subscriptions","Подписки","Subscriptions"),("Settings","Настройки","Settings"),
        ("ServerTitle","Выбор сервера","Choose a server"),("ServerSubtitle","Узлы из вашей подписки","Nodes from your subscription"),("SearchServers","Поиск сервера","Search servers"),("ByLatency","По пингу","By latency"),("ByName","По названию","By name"),("Fast","Быстрый","Fast"),("Exact","VPN (точный)","VPN (exact)"),
        ("RoutingTitle","Маршрутизация","Routing"),("RoutingSubtitle","Куда направлять трафик","Where your traffic goes"),("EntirePc","Весь ПК","Entire PC"),("EntireDetail","Весь трафик через VPN","All traffic through VPN"),("ByRules","По правилам","By rules"),("RulesDetail","Остальное — напрямую","Everything else goes direct"),
        ("Applications","Приложения","Applications"),("ApplicationsDetail","Выберите программы, которые будут идти через VPN","Choose programs that use VPN"),("Open","Открыть","Open"),("Presets","Готовые правила","Service presets"),("PresetsDetail","Telegram, YouTube, Discord, ChatGPT, Claude…","Telegram, YouTube, Discord, ChatGPT, Claude…"),("AddPreset","Добавить набор","Add a preset"),("MyRules","Мои правила","My rules"),("Add","Добавить","Add"),("CreateProfile","Создать профиль","Create profile"),("SearchRules","Поиск по правилам","Search rules"),("RuleTip","Правила сверху имеют приоритет. Перетащите строку, чтобы изменить порядок.","Higher rules take priority. Drag a row to reorder."),
        ("AddSubscription","Добавить подписку","Add subscription"),("SubscriptionDetail","Вставьте ссылку провайдера — серверы появятся автоматически","Paste your provider link to load servers"),("Update","Обновить","Update"),("Edit","Изменить","Edit"),("Delete","Удалить","Delete"),("NoSubscriptions","Здесь появится ваша подписка","Your subscription will appear here"),("NoServers","Добавьте первую подписку","Add your first subscription"),("NoServersDetail","Ссылка Ultima или любого VLESS-провайдера","Ultima or any VLESS provider link"),("NoRules","Добавьте сайты или приложения","Add websites or applications"),("NoRulesDetail","Без правил весь трафик идёт напрямую","Without rules all traffic goes direct"),
        ("Server","СЕРВЕР","SERVER"),("Mode","РЕЖИМ","MODE"),("Session","сессия","session"),("VpnIp","VPN IP-АДРЕС","VPN IP ADDRESS"),("VpnIpDetail","Проверка через выбранный сервер · без геолокации","Checked through the selected server · no geolocation"),("Mbps","Мбит/с","Mbps"),("Proxy","Прокси","Proxy"),
        ("SettingsDetail","Просто, безопасно и под вашим контролем","Simple, secure and under your control"),("Language","Язык","Language"),("Startup","Запускать вместе с Windows","Start with Windows"),("Tray","Сворачивать в трей","Minimize to tray"),("AutoConnect","Подключаться автоматически","Connect automatically"),("RestoreServer","Восстанавливать последний сервер","Restore last server"),("Notifications","Показывать уведомления","Show notifications"),("DnsProtection","Защита DNS","DNS protection"),("DnsDetail","Прямой DNS для обычных сайтов, VPN DNS для выбранных","Direct DNS for normal sites, VPN DNS for selected sites"),("Advanced","Дополнительно","Advanced"),("Compatibility","Совместимость с Docker / VM","Docker / VM compatibility"),("ConfigFolder","Папка настроек","Settings folder"),("LogsFolder","Открыть логи","Open logs"),("RestartService","Перезапустить службу","Restart service"),("SaveSettings","Сохранить настройки","Save settings"),("ProxyNote","Прокси использует 127.0.0.1:17890. Правила приложений требуют TUN.","Proxy uses 127.0.0.1:17890. Application rules require TUN."),
        ("Import","Импорт профиля","Import profile"),("Export","Экспорт профиля","Export profile"),("DeleteProfile","Удалить профиль","Delete profile")
    ];
    public static void Set(string language) { English = language == "English"; foreach (var (key, ru, en) in Labels) Application.Current.Resources[key] = English ? en : ru; }
}
