<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <InternalsVisibleTo Include="Bebekon.Tests" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.0" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup><EmbeddedResource Include="../../resources/flags/countries.json" LogicalName="Bebekon.Core.Countries.json" /></ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="../../resources/geo/*-*.json" LogicalName="Bebekon.Core.Geo.%(Filename)%(Extension)" />
    <EmbeddedResource Include="../../resources/presets/services.json" LogicalName="Bebekon.Core.Presets.json" />
    <EmbeddedResource Include="../../resources/presets/admin.json" LogicalName="Bebekon.Core.Admin.json" />
  </ItemGroup>
</Project>
