cmake_minimum_required(VERSION 3.24)
set(CMAKE_PROJECT_TOP_LEVEL_INCLUDES "${TT_SOURCE}/cmake/conan_bootstrap.cmake")
project(bebekon_trusttunnel C CXX)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
add_subdirectory("${TT_SOURCE}" upstream)
add_library(bebekon_trusttunnel SHARED bridge.cpp)
target_include_directories(bebekon_trusttunnel PRIVATE "${TT_SOURCE}/platform/android/lib/src/main/cpp")
target_link_libraries(bebekon_trusttunnel PRIVATE vpnlibs_trusttunnel android log)
target_compile_options(bebekon_trusttunnel PRIVATE "-fvisibility=hidden")
target_link_options(bebekon_trusttunnel PRIVATE "-Wl,-z,max-page-size=16384" "-Wl,--exclude-libs,ALL")
